/*

 FIREBALL.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Fireball[] =
{
  0x00,0x00,0x06,0x06,0x09,0x0F,0xFB,0xFD,
  0x67,0x79,0x19,0x1F,0x06,0x06,0x00,0x00,
  0x00,0x00,0x06,0x06,0x09,0x0F,0x3B,0x3D,
  0x67,0x79,0xF9,0xFF,0x06,0x06,0x00,0x00
};

/* End of FIREBALL.C */
