/*

 FLYINGARTEFACT.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char FlyingArtefact[] =
{
  0x00,0x00,0x00,0x00,0x5A,0x5A,0x24,0x3C,
  0x34,0x2C,0x5A,0x5A,0x00,0x00,0x18,0x00,
  0x00,0x00,0x5A,0x5A,0x24,0x3C,0x2C,0x34,
  0x5A,0x5A,0x00,0x00,0x18,0x00,0x3C,0x00
};

/* End of FLYINGARTEFACT.C */
